services:
  bot:
    image: ghcr.io/code-oclock/ollamabot:latest
    restart: unless-stopped
    env_file:
      - /opt/mybot/.env
    network_mode: "host"  
    volumes:
      - /opt/mybot/data:/app/data
